### PR TITLE
Fix generator when using array instead of hash

### LINKED ISSUE #104: Generator isn't working for array values
When running:
```
rails g enumerate_it:enum CivilStatus single married divorced widower concubinage separated stable
```
I'm getting this error:
```
create  config/locales/civil_status.yml
/.../enumerate_it-3.2.3/lib/generators/enumerate_it/enum/enum_generator.rb:37:in `fields': undefined method `type' for nil:NilClass (NoMethodError)

        if attributes.first.type == :string
                           ^^^^^
	from /.../enumerate_it-3.2.3/lib/generators/enumerate_it/enum/templates/enumerate_it.rb:3:in `template'
```
I tried to debug:
```ruby
def fields
  puts attributes # => nil
  puts args # => ["single", "married", "divorced", "widower", "concubinage", "separated", "stable"]
  
  if attributes.first.type == :string
    attributes.map(&:name)
  else
    attributes.map { |attribute| [attribute.name, attribute.type] }
  end
end
```

Looks like `argument :attributes, type: :hash` isn't working for arrays, just for hashes. I tried to change to `argument :attributes, type: :array` and worked fine. 

This PR https://github.com/lucascaton/enumerate_it/pull/103 changed from 'array' to :hash and broke. I did a search for `argument` method, but I didn't find anything about an argument accepts two types (hash and array), so I'm not sure how to solve it, but I will open a PR to discuss the solution.

Versions:
```ruby
# Gemfile.lock
...
enumerate_it (3.2.3)
      activesupport (>= 5.0.7.2)
...
rails (7.0.4)
...

RUBY VERSION
   ruby 3.1.2p20
```

### PR DESCRIPTION
**Pull request by stephannv**
The `argument :attributes, type: :hash` doesn't accept arrays, this generates an empty `attributes`. To solve this problem, the `args` (the array provided to generator) is returned when `attributes` is empty.

Closes #104,

### CODE REVIEW

File: lib/generators/enumerate_it/enum/enum_generator.rb [hunk 1]
```diff
@@ -29,12 +29,10 @@ def singular
         singular_name
       end
 
-      def locale_fields
-        attributes.map(&:name)
-      end
-
       def fields
-        if attributes.first.type == :string
+        if attributes.empty?
```
Comment (lucascaton) [inline lib/generators/enumerate_it/enum/enum_generator.rb:33]:
```suggestion
        if attributes.empty?
```

**Review by lucascaton — APPROVED** [review]
Sorry for the delay on this. Thanks, @stephannv! 🙌

**Comment by lucascaton** [comment]
A new version has been released with this fix: https://github.com/lucascaton/enumerate_it/releases/tag/v3.2.4

**Comment by stephannv** [comment]
> Sorry for the delay on this. Thanks, @stephannv! 🙌

No problem. Thanks for maintaining this project.
